# Site wide configuration

title: Teear
description: Teear &ndash; Radio and Web Stuff
logo: teear-logo.png # 120x120 px default image used for Twitter summary card
teaser: teaser.jpg # 400x250 px default teaser image used in image archive grid
locale:
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge # was pygments, must be rouge for GH Pages 16/03/2016
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Teear
  email:
  twitter: 56fl001
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
